import re
import httpx
from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class LinkRequest(BaseModel):
    url: str

def extract_content_id(url: str) -> str:
    match = re.search(r"gofile\.io/d/([a-zA-Z0-9]+)", url)
    if not match:
        raise HTTPException(status_code=400, detail="Invalid Gofile URL format")
    return match.group(1)

@app.post("/get-stream-link")
async def get_stream_link(request: LinkRequest, req_info: Request):
    content_id = extract_content_id(request.url)
    
    # Cloudflare bypass karne ke liye standard external proxy API gateways ka use
    # Ye public proxy API direct HTML/Cloudflare blocks ko strip kar deti hai
    bypass_urls = [
        f"https://api.allorigins.win/get?url={httpx.URL('https://api.gofile.io/getContents?contentId=' + content_id)}",
        f"https://corsproxy.io/?https://api.gofile.io/getContents?contentId={content_id}"
    ]
    
    async with httpx.AsyncClient(timeout=20.0, follow_redirects=True) as client:
        res_data = None
        for proxy_url in bypass_urls:
            try:
                response = await client.get(proxy_url)
                if response.status_code == 200:
                    json_data = response.json()
                    # Allorigins wrapper format check
                    if "contents" in json_data and isinstance(json_data["contents"], str):
                        import json
                        res_data = json.loads(json_data["contents"])
                    else:
                        res_data = json_data
                    
                    if res_data.get("status") == "ok":
                        break
            except Exception:
                continue

        if not res_data or res_data.get("status") != "ok":
            raise HTTPException(status_code=403, detail="Bypass failed: Gofile anti-bot system is too strong on this cluster.")

        try:
            contents = res_data["data"]["contents"]
            file_id = list(contents.keys())[0]
            file_info = contents[file_id]
            
            direct_link = file_info.get("link")
            if not direct_link:
                raise HTTPException(status_code=500, detail="No link generated by cluster node")
            
            base_url = str(req_info.base_url).rstrip("/")
            # Ye server side proxy streaming url return karega
            proxy_url = f"{base_url}/proxy-stream?stream_url={direct_link}"
                
            return {
                "status": "success",
                "file_name": file_info.get("name"),
                "stream_url": proxy_url
            }
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Data parsing error: {str(e)}")

@app.get("/proxy-stream")
async def proxy_stream(stream_url: str, request: Request):
    # Gofile CDN storage servers direct asset streaming ke liye standard generic headers accept karte hain
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
        "Accept": "*/*"
    }
    
    range_header = request.headers.get("Range")
    if range_header:
        headers["Range"] = range_header

    client = httpx.AsyncClient(timeout=60.0, follow_redirects=True)
    req = client.build_request("GET", stream_url, headers=headers)
    resp = await client.send(req, stream=True)
    
    response_headers = {
        "Accept-Ranges": resp.headers.get("Accept-Ranges", "bytes"),
        "Content-Type": resp.headers.get("Content-Type", "video/mp4"),
        "Content-Length": resp.headers.get("Content-Length"),
    }
    if resp.headers.get("Content-Range"):
        response_headers["Content-Range"] = resp.headers.get("Content-Range")

    async def stream_generator():
        try:
            async for chunk in resp.aiter_bytes(chunk_size=128 * 1024):
                yield chunk
        finally:
            await resp.aclose()
            await client.aclose()

    return StreamingResponse(stream_generator(), status_code=resp.status_code, headers=response_headers)
    
