import re
import httpx
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI()

# Frontend integration ke liye CORS enable kiya he
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class LinkRequest(BaseModel):
    url: str

BASE_HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "*/*",
    "Accept-Language": "en-US,en;q=0.9",
    "Origin": "https://gofile.io",
    "Referer": "https://gofile.io/"
}

def extract_content_id(url: str) -> str:
    """Gofile URL se real content ID nikalne ka logic"""
    match = re.search(r"gofile\.io/d/([a-zA-Z0-9]+)", url)
    if not match:
        raise HTTPException(status_code=400, detail="Invalid Gofile URL format")
    return match.group(1)

async def create_gofile_guest_token(client: httpx.AsyncClient) -> str:
    """Real Logic: Gofile server par guest account session generate karna"""
    try:
        response = await client.post("https://api.gofile.io/accounts", headers=BASE_HEADERS)
        data = response.json()
        if data.get("status") == "ok":
            return data["data"]["token"]
        raise HTTPException(status_code=500, detail="Failed to create Gofile guest token")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Token generation error: {str(e)}")

@app.post("/get-stream-link")
async def get_stream_link(request: LinkRequest):
    content_id = extract_content_id(request.url)
    
    async with httpx.AsyncClient(timeout=15.0) as client:
        # 1. Token nikalo
        token = await create_gofile_guest_token(client)
        
        # 2. Token ko headers me inject karo authorize karne ke liye
        headers = BASE_HEADERS.copy()
        headers["Authorization"] = f"Bearer {token}"
        
        # 3. Gofile ki internal content api se real metadata khincho
        api_url = f"https://api.gofile.io/getContents?contentId={content_id}"
        try:
            response = await client.get(api_url, headers=headers)
            res_data = response.json()
            
            if res_data.get("status") != "ok":
                raise HTTPException(status_code=400, detail=f"Gofile API Error: {res_data.get('status')}")
                
            contents = res_data["data"]["contents"]
            if not contents:
                raise HTTPException(status_code=404, detail="No files found in this link")
            
            # Pehli video file ka content pick karo
            file_id = list(contents.keys())[0]
            file_info = contents[file_id]
            
            direct_link = file_info.get("link")
            file_name = file_info.get("name")
            
            if not direct_link:
                raise HTTPException(status_code=500, detail="Direct link not generated by Gofile")
                
            return {
                "status": "success",
                "file_name": file_name,
                "stream_url": direct_link,
                "token_used": token
            }
            
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Processing failed: {str(e)}")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
  
